version: "3.8"
services:
  db:
    image: postgres:12
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: resume_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - nat

  backend:
    build: ./hackathon-backend
    ports:
      - "5000:5000"
    volumes:
      - ./hackathon-backend:/app
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST=db
      - POSTGRES_DB=resume_db
      - DATABASE_URL=postgresql://user:password@db:5432/resume_db
    depends_on:
      - db
    networks:
      - nat
    # command: >
    #   sh -c "python -m spacy download en_core_web_sm && python app.py"

  frontend:
    build: ./hackathon-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./hackathon-frontend:/app
    depends_on:
      - backend
    # command: npm start
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - nat
  admin:
      image: adminer
      restart: always
      depends_on:
        - db
      ports:
       - 8080:8080
      networks:
        - nat


volumes:
  postgres_data:

networks:
  nat:
    driver: bridge
